name: idiotas
favicon: null
layout_spectrum: 0.49765
typography_spectrum: 0.8297521383501589
title: 'Señor, protege a Panamá de los idiotas - Por Miguel A. Esquivel K. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#c40001'
    - '#494949'
    - '#f5c4b5'
  brandStrength: 0.5
  lightness: 0.5416644799988717
  saturation: 0
  rhythmicContrast: 0.8497083787806332
purpose: []
