name: idiotas
favicon: null
layout_spectrum: 0.2582
typography_spectrum: 0.8297521383501589
title: 'Señor, protege a Panamá de los idiotas'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c40001'
    - '#010101'
    - '#cf968b'
    - '#72382c'
  brandStrength: 0.38005956588312984
  lightness: 0.5416644799988717
  saturation: 0.17114974511787295
  rhythmicContrast: 0.8497083787806332
purpose: []
